# Kleaf custom modules for transsion project
def get_tran_custom_modules_list(
        kleaf_modules,
        kleaf_user_modules,
        kleaf_userdebug_modules,
        kleaf_eng_modules,
        device_modules,
        device_user_modules,
        device_userdebug_modules,
        device_eng_modules,
        platform_device_modules,
        platform_device_user_modules,
        platform_device_userdebug_modules,
        platform_device_eng_modules,
        common_modules,
        common_user_modules,
        common_userdebug_modules,
        common_eng_modules):
    device_modules.append("sound/soc/transsion/hl1280.ko")
    device_modules.append("sound/soc/transsion/fs1599/snd-soc-fs1599.ko")
    device_modules.append("sound/soc/transsion/tran_audio_control/tran_audio_control.ko")
    device_modules.append("sound/soc/transsion/elliptic/elliptic-ultrasound.ko")
    device_modules.append("drivers/regulator/et5904.ko")
    device_modules.append("drivers/misc/mediatek/flashlight/v4l2/ocp81378.ko")
    device_modules.append("drivers/misc/mediatek/flashlight/v4l2/aw36515.ko")
    device_modules.append("drivers/misc/mediatek/flashlight/v4l2/ocp81375.ko")
    device_modules.append("drivers/misc/mediatek/flashlight/v4l2/awt36515.ko")
    device_modules.append("drivers/misc/mediatek/flashlight/v4l2/cw8722.ko")
    device_modules.append("drivers/misc/mediatek/flashlight/v4l2/sgm37864.ko")
    device_modules.append("drivers/gpu/drm/panel/rm692j0_fhdp_dsi_cmd_dsc_boe_boe_144hz_lj9.ko")
    device_modules.append("drivers/gpu/drm/panel/rm692j0_fhdp_dsi_cmd_dsc_boe2_boe_144hz_lj9.ko")
    device_modules.append("drivers/misc/mediatek/sensor/2.0/sensor_debug/tran_sensor_debug.ko")
    device_modules.append("drivers/nfc/pn560/nfc_i2c.ko")
    device_modules.append("drivers/nfc/rn4v/sec_nfc.ko")
    device_modules.append("drivers/misc/mediatek/trancam_driver_elapsedtime/trancam_driver_elapsedtime.ko")
    device_modules.append("drivers/gpu/drm/panel/ft8725_fhdp_dsi_vdo_txd_boe_144hz_lj7.ko")
    device_modules.append("drivers/gpu/drm/panel/nt37703a_fhdp_dsi_vdo_tm_tm_144hz_cm7.ko")
    device_modules.append("drivers/gpu/drm/panel/nt37703a_fhdp_dsi_vdo_tm_tm_144hz_lj8k.ko")
    device_modules.append("drivers/gpu/drm/panel/nt37703a_fhdp_dsi_vdo_tm_tm_144hz_x6856.ko")
    device_modules.append("drivers/gpu/drm/panel/nt37703a_fhdp_dsi_vdo_tm_tm_144hz_x6870.ko")
    device_modules.append("drivers/gpu/drm/panel/rm692j0_fhdp_dsi_cmd_dsc_boe_boe_144hz_cm8.ko")
    device_modules.append("drivers/gpu/drm/panel/td4160_hdp_dsi_vdo_txd_inx_120hz_x6857.ko")
    device_modules.append("drivers/gpu/drm/panel/tran_drm_i2c_drv/tran_drm_panel_i2c.ko")
    device_modules.append("drivers/gpu/drm/panel/vtdr6126a_fhdp1224x2720_dsi_vdo_tm_144hz_lj8.ko")
    device_modules.append("drivers/gpu/drm/panel/vtdr6126a_fhdp1224x2720_dsi_vdo_tm_144hz_x6873.ko")
    device_modules.append("drivers/gpu/drm/panel/vtdr6126a_fhdp1224x2720_dsi_vdo_tm_144hz_x6876.ko")
    device_modules.append("sound/soc/transsion/aw87xxx/snd-soc-aw87xxx.ko")
    device_modules.append("sound/soc/transsion/aw883xx/snd-soc-aw883xx.ko")
    device_modules.append("sound/soc/transsion/oca72xxx/snd-soc-oca72xxx.ko")
    device_modules.append("sound/soc/transsion/splitswitch/splitswitch.ko")
    device_modules.append("sound/soc/transsion/was4783c.ko")
    device_modules.append("drivers/input/touchscreen/fold_project/flip_fold/ft3683g_spi_main_touch/ft3683g_spi_main.ko")
    device_modules.append("drivers/input/touchscreen/fold_project/flip_fold/gt9615_spi_sub_touch/goodix_spi_sub.ko")
    device_modules.append("drivers/input/touchscreen/fold_project/fold_touch/fold_touch.ko")
    device_modules.append("drivers/input/keyboard/aw9620x/aw9620x.ko")
    device_modules.append("drivers/leds/aw862xx/aw86224_light.ko")
    device_modules.append("drivers/misc/mediatek/aw95016/aw95016.ko")
    device_modules.append("drivers/misc/mediatek/hall_holster/hall_holster.ko")
    device_modules.append("drivers/misc/mediatek/hall_rlk/line_hall.ko")
    device_modules.append("drivers/misc/mediatek/sensor/hr_spo2/tran_hr_spo2/tran_hr_spo2.ko")
    device_modules.append("drivers/misc/mediatek/tran_lra/aac_haptic_hv/haptic_drv_hv.ko")
    device_modules.append("drivers/regulator/dio8018.ko")
    device_modules.append("drivers/misc/mediatek/tetras_aiisp/ipc/tetras_ipc.ko")
    device_modules.append("drivers/misc/mediatek/tetras_aiisp/linux-ext/ai_isp_pmctrl/pmctrl.ko")
    device_modules.append("drivers/misc/mediatek/tetras_aiisp/linux-ext/aiisp_drv/cam_ai_isp.ko")
    device_modules.append("drivers/misc/mediatek/tetras_aiisp/linux-ext/communication/communication.ko")
    device_modules.append("drivers/misc/mediatek/tetras_aiisp/linux-ext/sdio2axi/sdiobridge.ko")
    device_modules.append("drivers/misc/mediatek/tetras_aiisp/linux-ext/tetras_ls_socbridge/spibridge.ko")
