# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the touchscreen drivers.
#
obj-$(CONFIG_TRAN_TOUCH_CORE) += core/

#focaltech
obj-$(CONFIG_TRAN_FT3683G_SPI) += vendor/focaltech/ft3683g_spi/
obj-$(CONFIG_TRAN_FOCALTECH_NO_FLASH_COMMON) += vendor/focaltech/focaltech_no_flash_common/

#goodix
obj-$(CONFIG_TRAN_GT9916_SPI) += vendor/goodix/gt9916_common/

#omnivision
obj-$(CONFIG_TRAN_TD4160_SPI) += vendor/omnivision/td4160_common/
obj-$(CONFIG_TRAN_TD4376_SPI) += vendor/omnivision/td4376_common/
