$(warning #tran_hiber#: $(CONFIG_TRAN_HIBER_SUPPORT))
ccflags-y += -I$(srctree)/
obj-$(CONFIG_TRAN_HIBER_SUPPORT) += hiber.o
hiber-y += tran_hiber.o tran_netfilter.o hiber_help.o

$(warning #tran_hiber#: obj-$(CONFIG_TRAN_HIBER_SUPPORT))
