##############################################################################
#
# (C) Copyright 2021, Shenzhen Tetras.AI Technology Co., Ltd
#
# Makefile for Tetras driver.
#
# Change Logs:
# Date           Author       Notes
# 2021-12-30     yanghua      Initialize.
#
##############################################################################
obj-y += tetras_ls_socbridge/
obj-y += sdio2axi/
obj-y += communication/
obj-y += aiisp_drv/
obj-y += ai_isp_pmctrl/
