ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/typec/tcpc/inc
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/power/supply/transsion
obj-m += splitswitch-gpio.o

obj-$(CONFIG_USB_SWITCH_DIO1520) += splitswitch.o
