// SPDX-License-Identifier: GPL-2.0-only
/*
 * Copyright (C) 2019 Transsion Inc.
 */

#ifndef __LINUX_TC_WATER_DETECT_H
#define __LINUX_TC_WATER_DETECT_H

enum {
	SCHEME_SUBPMIC = 0,
	SCHEME_GPIO,
	SCHEME_GPIO_AND_SBU_1_2,
	SCHEME_USB_SWITCH,
	SCHEME_USB_ID_AND_GPIO,
	SCHEME_USB_ID_AND_GPIO_AND_SBU_1_2,
};

enum {
	WD_USER_CMD_UNKNOWN = 0,
	WD_USER_FORCE_CHARGING = 5,
	WD_USER_DISCHARGING = 10,
};

enum {
	WD_TRIGGER = 0,
	WD_USER_SELECT_FORCE_CHARGING,
	WD_USER_SELECT_DISCHARGING,
};


#endif

