# SPDX-License-Identifier: GPL-2.0
#
# Makefile for misc devices that really don't fit anywhere else.
#

#SDD:add for tnek.ko by yanbin.zhang 2024/07/18 start
obj-$(CONFIG_TRAN_TNEK_SUPPORT) += transsion/
#SDD:add for tnek.ko by yanbin.zhang 2024/07/18 end
obj-y				+= mediatek/




obj-y                           += hiber/



