#
# Transsion Top Secret
# Copyright (C) 2022 Transsion Inc.
#
# @Description : interface of statistical time interval for camera driver
#
# @Author      : wei.miao@transsion.com
# @Version     : 2022-06-01
#
#

obj-m += trancam_driver_elapsedtime.o
